### PR TITLE
Remove unused code, optimize imports, fix Codacy issues

### PR DESCRIPTION
**Pull request by cascer1**

### CODE REVIEW

**Comment by RobWin** [comment]
Did you remove the DocumentationTest? The test is used by the AsciiDoc documentation.

**Comment by cascer1** [comment]
Looks like it was removed indeed :o 

Strange how I didn't get any exceptions when running the tests before submitting this PR. I'll add them again!

**Comment by RobWin** [comment]
The DocTest veryfies that the examples, which are included into the documentation, are compileable.

**Comment by RobWin** [comment]
Btw if you plan to contribute more and be part of the contributor team, I can invite you to our Slack channel.

**Comment by cascer1** [comment]
Sure, that'd be cool! I have a few more things on my list that I'd like to implement. 

Feel free to invite my profile email on github, without the +github suffix.

**Pull request merged**
