### PR TITLE
Added output files language option

### PR DESCRIPTION
**Pull request by MeteorBoom**
Can you check my changes? Tell me what to fix if something wrong or if I need to add sth.

### CODE REVIEW

**Comment by MeteorBoom** [comment]
Maybe to merge properties file in one? From other hand it will be longer.

**Comment by RobWin** [comment]
Yes, please merge everything into one property file and use a `PropertiesResourceBundle` instead of the `Properties` class.
See https://docs.oracle.com/javase/7/docs/api/java/util/PropertyResourceBundle.html and https://docs.oracle.com/javase/tutorial/i18n/intro/steps.html

**Comment by RobWin** [comment]
The `Language` enum could have a `Locale` instead of a String as a property.

**Comment by MeteorBoom** [comment]
OK. I will fix it.

**Pull request merged**
