### PR TITLE
Allow auto-generation of examples

### PR DESCRIPTION
**Pull request by erikhakansson**
This will parse examples from Swagger input, using the various .getExample() methods.

### CODE REVIEW

**Comment by RobWin** [comment]
Thx for your Pull Request. I have a look at it.

**Comment by RobWin** [comment]
I created a new PR, but merge it into a new branch called `examples`

**Comment by RobWin** [comment]
Btw. If you like Swagger2Markup, I would love to get your GitHub star :)

**Comment by RobWin** [comment]
If you like you can also join https://gitter.im/Swagger2Markup/swagger2markup.
We can talk about your changes there.

**Comment by erikhakansson** [comment]
@RobWin starred! :)

Anyway, regarding an example swagger file, I'll try to cook one up. The swagger.json from Pet Store already contains a single example, though so that should work at least. It only contains a single type of example, though, so I'll try to modify it to add some more. It might take a little while though, as I have a bit on my plate at work right now.

**Comment by RobWin** [comment]
Examples for model definitions (schema objects) and response objects would be nice.
But I don't think that your new feature should replace the examples which are generated by Spring rest-docs (request, response, curl snippets). You should be able to use both.
Examples which are included in the Swagger file should be rendered by default, if they are available.
Spring Rest-Docs can be used additionally, if you use the Spring Stack.

**Pull request closed without merging**
