### PR TITLE
Adding support for Brazilian Portuguese Language

### PR DESCRIPTION
**Pull request by cleydsonjr**
Fixing Issue #200

### CODE REVIEW

**Comment by RobWin** [comment]
Hi, thx. Could you please convert the file into latin1 by using the tool native2ascii?

Btw if you like Swagger2markup, we would love to get your GitHub Stars.

**Comment by cleydsonjr** [comment]
Hi @RobWin. I did what you asked. Can you check please?

And the star. :+1:

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
I've added Portuguese (Brazilian). You can select the language as follows:

```
Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
                .withOutputLanguage(Language.BR)
                .build();
        Swagger2MarkupConverter.from(file)
                .withConfig(config)
                .build()
                .toFolder(outputDirectory);
```

1.1.1-SNAPSHOT

**Pull request merged**
