### PR TITLE
fixing complaints of javadoc about autoclosing tags

### PR DESCRIPTION
**Pull request by ahus1**
Testing it locally gradle's javadoc complained about auto-closing tags that would not be allowed within javadoc. Therefore i removed the autoclosing element.

### CODE REVIEW

**Comment by ahus1** [comment]
I don't know why it sees a conflict here... please advise on how to update the PR to avoid this message.

**Comment by RobWin** [comment]
Hi, it's because you use Java8 to compile.

**Comment by RobWin** [comment]
Good question.

**Comment by RobWin** [comment]
Fixed

**Pull request closed without merging**
