### PR TITLE
labels_zh.properties

### PR DESCRIPTION
**Pull request by mingkaili**
Add chinese labels.properties. Add chinese language.

### CODE REVIEW

**Comment by RobWin** [comment]
Thx

**Comment by mingkaili** [comment]
@RobWin You`re welcome!! Have what I commited been merged to master by you? When I can use it?

**Comment by mingkaili** [comment]
@coveralls @RobWin Oh my god! I see it that what I committed. Thank everyboby!!!! I want to test it right now!!

**Comment by RobWin** [comment]
It should be available as `1.0.2-SNAPSHOT` now.

See http://swagger2markup.github.io/swagger2markup/1.0.1/#_getting_started

**Comment by mingkaili** [comment]
@RobWin Thank you!!

**Comment by RobWin** [comment]
You are welcome. Thanks for your contribution

**Pull request merged**
