### PR TITLE
Fix for StackOverflow when examples have cyclic references

### PR DESCRIPTION
**Pull request by mhswisscom**
Hi. I had troubles generating documentation with examples when a resource included itself. The code for the example creation does not stop when cyclic references are used. Now there is a constant in ExampleUtil that restricts the depth of the example to a certain level so that the recursion is visible but stops at a certain level (only "..." is displayed in the example when the max depth is reached).

Regards
Marc

PS: Sorry for the code reformating...

### CODE REVIEW

**Comment by RobWin** [comment]
Hi, thx.

I created an issue to track this PR.

https://github.com/Swagger2Markup/swagger2markup/issues/173

**Comment by RobWin** [comment]
Could you please check the tests, `testSwagger2AsciiDocConversionInstagram` is failing. Why did you change the expected file `overview.adoc`? Does it run fine locally with your change?

**Comment by mhswisscom** [comment]
Yes, the test runs fine locally after my change in overview.adoc.

io.github.swagger2markup 	36 	0 	0 	7.709s 	100%
io.github.swagger2markup.builder 	5 	0 	0 	0.027s 	100%

Perhaps a plattform issue, i have no changes left to commit.

**Comment by RobWin** [comment]
Btw, if you like and use Swagger2markup, we would love to get your GitHub Star.

**Comment by RobWin** [comment]
The failing test must have a Problem with Windows and Linux line separator.
Do you use Windows? The files are stored with LF. Does your git config convert them to CRLF?

**Comment by mhswisscom** [comment]
I've set the option core.autocrlf=true so it should convert the line endings automatically, but i don't understand why it is only in that testcase an issue. I we had troubles with line endings i would expect more errors in the file comparison.
My build environment is Windows 7 & Java 8.

Btw., you got my GitHub Star ;-)

**Comment by RobWin** [comment]
True. I have to investigate it further.

**Comment by RobWin** [comment]
Do you think you could generate a new PR which does not change code formatting?

**Comment by mhswisscom** [comment]
sure, give me some minutes

**Comment by RobWin** [comment]
:+1:

**Pull request closed without merging**
