### PR TITLE
Polish language translation

### PR DESCRIPTION
**Pull request by michaldul**
This the first version of the translation. The more apis I will document with this the better it will be.

### CODE REVIEW

**Comment by RobWin** [comment]
Thx. Could you please also add polish to the language builder?

**Comment by RobWin** [comment]
https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/swagger2markup/Language.java

**Comment by michaldul** [comment]
@RobWin thanks for notice. PR updated.

**Comment by michaldul** [comment]
@RobWin can you tell when it will be released? Or have any tips on how to modify swagger2markup-cli/build.gradle so that it would use latest master version?

**Comment by lkolek** [comment]
Michal, first: thanks for commiting. Yet properties are encoding in UTF-8 and ResourceBundle doesn't handle that properly. Second, you can use it using SNAPSHOT version - eg. for swagger2markup-gradle-plugin:

        classpath("io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3"){
            exclude module: 'io.github.swagger2markup:swagger2markup'
        }
        classpath ('io.github.swagger2markup:swagger2markup:1.3.4-SNAPSHOT')

**Pull request merged**
