### PR TITLE
Improve the zh_CN translation.

### PR DESCRIPTION
**Pull request by shardings**
For human:
default_column: 默认列 -> 默认值
example_column: 例子 -> 样例
schema_column: 架构 -> 类型
overview: 概观 -> 概览

### CODE REVIEW

**Comment by shardings** [comment]
@RobWin 
As I say in the comment. 
The translation of overiview "概观" is a too official word and almost only used in the name of a serious book. It is not suitable to be used here.
The translation of scheme "架构" actually means "architecture" in Chinese, it is wrong.
The translation of example "例子" actually means "for example", it is not precision.
The translation of default_column "默认列" should ignore the column("列"), and "默认" is a verb in Chinese (means " tacitly approve"). "默认值" should be the right one which means "default value".

**Comment by RobWin** [comment]
Thx

**Comment by mingchen** [comment]
Hi @shardings, how about translate 'overview' to 概述 ?

**Comment by mingchen** [comment]
Hi @RobWin, It seems this change does not included in the latest release 1.3.1 ? I still get old translation with 1.3.1.

**Pull request merged**
